apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-service-config
data:
  JWT_ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: appointment_service
